repo: "horizontal-nav"
canvasCourse: "467502"
canvasAssignment: "4178296"

naming: true
commits: 2

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - "header"
      - "header h1"
      - "header nav"
      - "header nav ul"
      - "header nav ul li a"
    search:
      - "Bevan"
      - "Planets"
      - "Introduction"
      - "Terrestrial planets"
      - "Mars"
      - "Venus"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
      - ["html", "box-sizing", "border-box"]
      - ["body", "margin", "0"]
    search:
      - "Bevan"
      - "margin"
      - "padding"
      - "background-color"
      - "list-style-type"
      - "display"
      - "inline-block"
      - "border"
      - "border-radius"
